name: Rust

on: [push]

jobs:
  build:

    runs-on: [macos, linux, windows]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
